### ISSUE TITLE
this.dateMenu.get_parent() is null

### ISSUE THREAD

**Issue by jwdotpark** [Aylur/gnome-extensions#10]
Hi, first thank you so much for the great extension.

With recent update, I get this error: `this.dateMenu.get_parent() is null`. 

Although I do have default topbar clock, I can't understand why it isn't able to grab the parent. Checked out the code `dateMenuMod.js`.. probably it isn't properly reset when disabled/reloaded on boot? 

Any help would be appreciated, thanks!

**Comment by Aylur** [comment]
I got that error once, but I don't get why because I don't remember editing that part.
Disabling the extension, loggin in and out then enabling seemed to fix it for me.

**Comment by jwdotpark** [comment]
> Disabling the extension, loggin in and out then enabling seemed to fix it for me.

Tried that but wasn't able to re-enable it, error was persistent.. but I switched out the code where error was there with prev commit - probably right before the recent updated one and now it works as intended.

Thank you for the help!
