### ISSUE TITLE
Volume adjusting doesnt work

### ISSUE THREAD

**Issue by thivmcthiv2** [Aylur/gnome-extensions#16]
OS: Ubuntu 22.04
Gnome: 42.5
Windowing system: X11

The volume in the dashboard always appears to be at 100%, and I am unable to adjust it.
Attempting to adjust it causes unexpected behavior like the spot spotify client crashing.

**Comment by Aylur** [comment]
The issue is with the Spot client, so for now I've put it on a blacklist for the volume part.
