### ISSUE TITLE
Power buttons (Power Menu) in color for Gtk4 Ding ?

### ISSUE THREAD

**Issue by Tuxman2** [Aylur/gnome-extensions#18]
Hi,

is there a way to have the power buttons (sleep, restart, shutdown, log out) in color ? All are in white.

Thanks.

**Comment by Aylur** [comment]
you can now do

    .restart StIcon{ color: red; }
    .power-off StIcon{ color: green; }
    .suspend StIcon{ color: magenta; }
    .logout StIcon{ color: yellow; }
    
will soon update on extensions.org too
