### ISSUE TITLE
Track widget in wrong offset

### ISSUE THREAD

**Issue by NashiraDeer** [Aylur/gnome-extensions#21]
Everytime that I reboot my PC the Music Track widget goes to a wrong offset, returning to normal when I edit it.

![image](https://user-images.githubusercontent.com/50382775/205163645-17460930-c576-46f4-9e17-3aa83f60aeac.png)
![image](https://user-images.githubusercontent.com/50382775/205163860-0ff0c1b9-e2d9-4cf7-b891-03434eed1de5.png)
![image](https://user-images.githubusercontent.com/50382775/205163998-12a82536-2dc0-4b06-b787-9d4617f5743f.png)

**Comment by Aylur** [comment]
Are there anything else that is set to the same offset?

**Comment by NashiraDeer** [comment]
No, I set different offset for each widget
