### ISSUE TITLE
Shell crashing(sometimes loging out user) when adjusting volume from media controls on Spotube

### ISSUE THREAD

**Issue by Gold3nF3nix** [Aylur/gnome-extensions#3]
[Video](https://vimeo.com/manage/videos/750702970)
Distro: Fedora 36 with Gnome 43rc

**Comment by Aylur** [comment]
I noticied this behavior with spotify aswell, I am unsure why is this happening. I might just blacklist spotify from adjusting volume.

**Comment by XMelph** [comment]
Same thing.
(Also, the night light in Quick Settings always goes back to the "weak" part rather than how I leave it.)
