### ISSUE TITLE
No covers show up for Spotify (Flatpak)

### ISSUE THREAD

**Issue by stpnwf** [Aylur/gnome-extensions#31]
No covers show up for Spotify (Flatpak). It works for youtube videos though...

![Screenshot from 2023-01-04 16-24-42](https://user-images.githubusercontent.com/81482539/210606739-22a0b8ea-2826-44ad-ae5a-c5315b6ae79c.png)

**Comment by Aylur** [comment]
Weird, I also use the flatpak version of Spotify and haven't encountered anything like this.
Does it persists even after going on the next track?
Try clearing the cache.

**Comment by stpnwf** [comment]
Tried all that. Could it be missing Gstreamer plugins? I am testing this on a Vanilla OS live environment as I currently am on another Distro pre Gnome 40, and won't be able to install for a some time. Once I am able to install it on hardware I will report back if it the issue is still present. Thanks

**Comment by Aylur** [comment]
Loaded it in a vm and turns out on Vanilla OS ```Gio.File.copy_async``` fails for ```The specified location is not supported```. I will look into it later.

**Comment by stpnwf** [comment]
Hey sorry for the delay in getting back. The covers show up in Vanilla OS now. The only (minor) issue that I have is that the first song name is never displayed in the top bar. A - (dash) is shown until there is a song change, then it all works fine.

I looked into the cache folder and there is some random artwork named - that will show up when one clicks on the - in the top bar.
Unsure how much of this is expected behavior.

**Comment by Aylur** [comment]
The dash naming issue is because when Spotify loads up the title and artist returns an empty string for some reason, and since the cache is based on the name+artist it is going the cache whatever song is queued. I think I will just skip the cache process if the name+artist returns empty.
