### ISSUE TITLE
Option to hide the media player and the notifications from the calendar menu

### ISSUE THREAD

**Issue by stpnwf** [Aylur/gnome-extensions#32]
Please add an option to hide the media player and the notifications from this menu. I already have the notification counter enabled and the media player in the top bar. If anything, it would be more useful to have Today's calendar events, the Weather and World clock there instead.

![Screenshot from 2023-01-04 16-59-29](https://user-images.githubusercontent.com/81482539/210609081-91842c2b-c3d7-4186-9000-1900e6084f41.png)

I tried using Quick Settings Tweaker, but both extensions overlap...

 .

**Comment by Aylur** [comment]
You already can. You can find it in Date Menu Tweaks. Hide Stock Mpris hides the media player, Hide Notifications hides the whole left column.

**Comment by stpnwf** [comment]
Thank you, I had the Date Menu turned off bc I was using Frippery to move the clock. No need for it anymore. But while messing with it I found a couple bugs. Will report here but can create a new issue if you prefer:

I just want to replicate the default Gnome Date format (pic below), but push it to the right so there is room for your media player

![Screenshot from 2023-01-04 23-35-17 (copy)](https://user-images.githubusercontent.com/81482539/210691175-9a9daf5e-07ea-4959-8918-92d33662b486.png)

But this is what I accomplish with this `%b%e %H:%M` instead. 
![Screenshot from 2023-01-04 23-38-35](https://user-images.githubusercontent.com/81482539/210691406-63fe68da-19c0-4e9c-a968-a814348ebdee.png)

I know I need a double space after the day, I just used one for contrasting that %e has so many spaces by itself... `%e` = `  4`, which I believe is a bug.


I am not sure if this one is a bug though. But the notification dot still shows up and is not clickable nor is it next to the notification icon (where I'd expect it to be), which was confusing to me. 
![Screenshot from 2023-01-04 23-52-41](https://user-images.githubusercontent.com/81482539/210692006-ef736824-c41f-4fd3-b97a-34fde6163e05.png)

**Comment by Aylur** [comment]
For the format I am using ```GLib.DateTime.format```, you can find a full list [here](https://valadoc.org/glib-2.0/GLib.DateTime.format.html). It seems like ```%e``` and some others has spaces intentionally, it is technically not a bug.
A temporary solution could be modifying ```~/.local/share/gnome-shell/extensions/widgets@aylur/widgets/dateMenuTweaks.js```

on line 262 change ```this.wallclock = new GnomeDesktop.WallClock({ time_only: true });```
to ```this.wallclock = new GnomeDesktop.WallClock();```
and on line 297 change ```this.clock.text = GLib.DateTime.new_now_local().format(this.dateFormat);```
to ```this.clock.text = this.wallclock.get_clock();```

Restart the shell or log out and in again. Now it will use the default clock. Maybe I will add an option next time to change it to the default one.

As for the notification dot you can hide it by changing the Indicator Position option in Date Menu Tweaks to Hide. The Notification Indicator part of the extension is independent from anything related to the clock or its menu, though I see why it would be confusing. Maybe it would make more sense to move those option to Notification Indicator.

**Comment by stpnwf** [comment]
Unsure if you can see from this video, unless I did something wrong, your suggestion did not work.
I couldn't get the mouse to show up...
[Screencast from 2023-01-07 00-04-00.webm](https://user-images.githubusercontent.com/81482539/211128779-f53a97b9-a723-4430-8ab3-e1638384b1ca.webm)

Regarding the notification I managed to hide the dot, thanks. Thought it was a bit confusing it wouldn't show up next to the notification icon. Glad I could turn it off then.

**Comment by stpnwf** [comment]
Hey, I saw that you updated the extension to include the option for the default Gnome date format. Much appreciated!
I noticed though that your implementation displays, for example, Feb **02**, when Gnome displays Feb **2** instead. Minor issue ofc. Reporting anyway.
