### ISSUE TITLE
Date Format with custom uppercase & spaces

### ISSUE THREAD

**Issue by CrimsonBloodfang** [Aylur/gnome-extensions#36]
Hello, I'm trying to use the font Anurati for the date format (%A) in background clock and I don't know how to make it all in uppercase. I also need each letter to have a space from each other.

As you can see, just placing %A doesn't showcase the full design of uppercase fonts like Anurati. I guess GNOME just provides the default lowercase fonts for custom fonts that don't have any?
![image](https://user-images.githubusercontent.com/68450471/216600642-4ee554a5-ea3c-47f4-885e-8ab95182b113.png)

Ideally, I would love to see it like this with a space in between each letter.
![image](https://user-images.githubusercontent.com/68450471/216601134-733e0f2c-d293-4903-9c41-aee50528632a.png)

If there are no spaces, the Anurati font would look like this.
![image](https://user-images.githubusercontent.com/68450471/216601395-8a9b42de-81cc-47e1-9b1d-605909c23a88.png)

I would really like an option in the extension for these specific use cases. If there are workarounds in the meantime, I'd like to know about it.

**Comment by Aylur** [comment]
I am using [GLib.DateTime.format](https://valadoc.org/glib-2.0/GLib.DateTime.format.html) which can't do things like this. You would need a function to return a custom string based on the day.
in ```~/.local/share/gnome-shell/extensions/widgets@aylur/widgets/backgroundClock.js``` at line 165
````js
    _updateClock(){
        let clock = GLib.DateTime.new_now_local().format(this._clockFormat);
        // let date = GLib.DateTime.new_now_local().format(this._dateFormat);

        this._clock.set_text(clock);
        // this._date.set_text(date);
        this._date.set_text(this._formatDay());
    }

    _formatDay(){
        //number between 1-7 as string
        let day = GLib.DateTime.new_now_local().format('%u');

        switch (day) {
            case '1': return 'M O N D A Y';
            case '2': return 'T U E S D A Y';
            //
            default: return '';
        }
    }
````

**Comment by CrimsonBloodfang** [comment]
@Aylur Thank you! It worked perfectly.
