### ISSUE TITLE
Issue on fedora details below

### ISSUE THREAD

**Issue by AyaanMAG** [Aylur/gnome-extensions#37]
![image](https://user-images.githubusercontent.com/63659414/216997654-4a2acdee-dc49-4aa2-b87e-ab9438e7c22c.png)

`this.dateMenu.get_parent() is null`

**Comment by Aylur** [comment]
if restarting the shell didn't help
try resetting the settings ```dconf reset -f /org/gnome/shell/extensions/aylurs-widgets/```
