### ISSUE TITLE
Translations missing in example.pot

### ISSUE THREAD

**Issue by Tuxman2** [Aylur/gnome-extensions#39]
Hello,

I translated the whole example.pot file in French. But some parts are still in English when I use your extension translated in French.

BackgroundClock:  Left, Center, Right, Hide.
batterBar: Left, Center, Right.
DashBoard: Left, Center, Right.
mediaPlayer: Left, Center, Right.
PowerMenu: Left, Center, Right.
workspaceindicator: Left, Center, Right.

Otherwise, all others items and strings are translated in French.

Can you check it ? Is it a bug ?

Thanks.

**Comment by Aylur** [comment]
Checked it out, found some parts where the translation wasn't being done, but the prefs wasn't one of them. Left, Center, Right should be translated
