### ISSUE TITLE
Add options to position dashboard Icons

### ISSUE THREAD

**Issue by ribua** [Aylur/gnome-extensions#41]
Hi , 

First of all, great extension love it. However I can't find an option to move the icon to the left or right and stays in the center for me all the time. 

Ribu

**Comment by ribua** [comment]
![dashboard](https://user-images.githubusercontent.com/41564422/224163330-57fa75a7-61e2-4968-a090-f0e627f5260e.png)

**Comment by Aylur** [comment]
Which icon are asking about exactly?

**Comment by ribua** [comment]
@Aylur  this is like the clock and also power button.

**Comment by ribua** [comment]
@Aylur  I think it is an issue on my end. Hence I am closing this issue. Thanks for your help.
