### ISSUE TITLE
Player icon missing after updating to 20.

### ISSUE THREAD

**Issue by axelvanherle** [Aylur/gnome-extensions#43]
![missing icon](https://user-images.githubusercontent.com/94362354/225555046-cb6e0bb5-6bda-4a00-93fd-a8dcbef3bbba.png)

After updating the player icon is missing.

Im on Linux pop-os 6.2.0-76060200-generic.
I have a theme applied, no other extensions should be interfering.

**Comment by Aylur** [comment]
Weird, I didn't touch anything releated to this from v19.
What is your gnome version?
What application doesn't show an icon? And how was that app installed flatpak/deb?

**Comment by axelvanherle** [comment]
I'm on GNOME Shell 42.5.

The application is Spotify, installed via flatpak.

**Comment by Aylur** [comment]
Seems like I had an icon pack applied when I was working on this and haven't encountered this issue.
I get the icon name from the MPRIS `entry` property which is 'spotify' in both the flatpak and non flatpak versions.
But the icon provided in flatpak is not `spotify.svg` but `com.spotify.Client.svg`. There is no way to check what version is running through MPRIS. I will add a generic fallback icon.
What you can do is apply an icon pack which provides `spotify.svg` for the colored version and `spotify-symbolic` for the noncolored version of the icon.
Or try installing spotify as a deb, though I am not sure if there is one or if it provides these icons.

**Comment by axelvanherle** [comment]
Thanks for the quick responses, for now i have just disabled the icon from showing, probably will keep it like that.

Thanks again for your help, and for your work on the extension.

**Comment by stpnwf** [comment]
Happens to me as well. Strangely enough the only icon that shows up for me is Spotify (flatpak) if and only if I have my custom icon pack applied. In every other situation I get this:
![Screenshot from 2023-03-16 19-56-50](https://user-images.githubusercontent.com/81482539/225773745-90ea5ccc-45d7-4a55-9c40-1db1f5303617.png)
I am on Fedora 37 (Gnome 43.3)

I didn't know it was possible to enable the icon to show up like that. Now I know it is possible, I love it. It suddenly started showing up after an update (v18 or 19 I think) and I noticed that it only worked for Spotify...

**Comment by Aylur** [comment]
It is based on the MPRIS entry property, for example on firefox this entry is `firefox` so it looks for `firefox` and `firefox-symbolic` icons based on your settings in the extension Media Player > Track Button > Colored Player Icon. For spotify it is `spotify` and `spotify-symbolic`.
The issue is that apps from flatpak provide icons named like `com.spotify.Client` or something but the entry is still `spotify`.

**Comment by stpnwf** [comment]
Hmm, I see. I think I personally slightly prefer the full on icons to show up, but regardless it is strange only Spotify shows up for me and not other flatpak icons.
