### ISSUE TITLE
Dash Features

### ISSUE THREAD

**Issue by bijo11235** [Aylur/gnome-extensions#5]
Could the dash be made customisable? For instance, there are only 5 preset links. I would like for these links to be customisable. Really great extension by the way, I love it!

**Comment by bijo11235** [comment]
Also, the temperature icon isn't being displayed properly on mu Ubuntu 22.04 system. 
![image](https://user-images.githubusercontent.com/86283091/194500088-55c1488b-d1cf-4e46-95cf-0b18d4fa4749.png)

**Comment by Aylur** [comment]
You can change the links through dconf-editor. I will try to add some settings releated to them to the extension prefs sometime soon.

**Comment by Aylur** [comment]
Also, I am not sure how to deal with the Icon since it is caused by whatever Icon pack Ubuntu is using.
