### ISSUE TITLE
Parent is null error

### ISSUE THREAD

**Issue by hmajid2301** [Aylur/gnome-extensions#52]
Whenever I restart my PC I get the following error `this.dateMenu.get_parent() is null`. I can fix it by reinstalling the plugin, but this of course is a real pain. 

Any ideas of what I can do ? (I'm sure if I there are any logs you want me to share)

Thanks

P.S. Love the extensions its amazing :heart: !!!!

Edit: Link to my gnome config for this extension: https://gitlab.com/hmajid2301/dotfiles/-/blob/main/gnome/settings.ini#L854-1033

**Comment by Aylur** [comment]
What other extensions are you using that does something with the panel or the date button?

**Comment by hmajid2301** [comment]
I cannot think of anything doing except maybe the gnome order extension?

Here is a list of my current setup; 
![image](https://user-images.githubusercontent.com/998807/234358571-a0347f1e-1793-47cd-b48d-920517e317cb.png)
