### ISSUE TITLE
2 bad extra spaces before the %e day number in date format

### ISSUE THREAD

**Issue by Yoannjap** [Aylur/gnome-extensions#59]
Brilliant extension!

One 'bug' for me, on date format, if I put '%a %e', there are 2 ugly extra spaces before the numer of the day (whereas if I put '%a %d', there is no extra spaces before the nuber).

May you fix it ?

Thanks a lot !

**Comment by Aylur** [comment]
I am using [GLib.DateTime.format](https://docs.gtk.org/glib/method.DateTime.format.html), it is not my implementation. `%e` is padded on single digits

**Comment by Yoannjap** [comment]
Ok, I didn't know this language.

Thank you for your reply wathever :)
