### ISSUE TITLE
Possible incompatibility with dash to panel

### ISSUE THREAD

**Issue by 4JX** [Aylur/gnome-extensions#61]
Currently using both extensions together, doing any of:
- Enabling Aylur's after Dash to Panel
- Altering any date menu related option
- Locking/Suspending and restarting the session after some time

Will leave the date button inaccessible until I restart Dash to Dock. 

Journalctl does produce [logs](https://gist.github.com/4JX/959ebd279f3f86a0e7b1ed408aee2d7d) for the first case, but they seem mostly unrelated.

Not sure which one is to blame, but disabling Aylur's after the issue is triggered keeps the issue present.

[Screencast from 2023-06-07 02-15-15.webm](https://github.com/Aylur/gnome-extensions/assets/79868816/1f888e00-f997-4198-a953-959c1cef7c38)

Current settings for both can be found [here](https://github.com/4JX/nixos-config/blob/333ee7c93f42fdaf262d3cbb1ab80d824a443355/modules/gnome/extensions/list.nix) (the others were disabled for this test, the aylur fork just has the extra patch applied from #53)

**Comment by Aylur** [comment]
I would recommend using [App Icon Taskbar](https://extensions.gnome.org/extension/4944/app-icons-taskbar) instead.
