### ISSUE TITLE
Date Menu Tweaks - Show Real Name button not working and maybe wrong position

### ISSUE THREAD

**Issue by D3vil0p3r** [Aylur/gnome-extensions#62]
Hey @Aylur. Thank you for managing https://github.com/Aylur/gnome-extensions/issues/58#issuecomment-1582930264

I'm just seeing maybe two issues related to Date Menu Tweaks and the Show Real Name:
1- currently, "Show Real Name" is under "Show User Icon" but I think they should be separated right? Furthermore, when the "Show User Icon" is not expanded, I see the up arrow instead of the down arrow icon. So, "up arrow" icon remains for both expanded and not expanded view of "Show User Icon".
2- when I enable "Show Real Name", the effect on the Date Menu Tweak is not applied immediately but only after the reboot. I don't know if it is expected.

**Comment by Aylur** [comment]
The arrow is an Adwaita thing, I can't change it. Seems like the Adw.ExpanderRow was not meant to be nested, haven't noticed it untill now.
I put it under `Show User Icon` because if it is not enabled, the `Show Real Name` won't change anything.
