### ISSUE TITLE
Missing Avatar image from Dash

### ISSUE THREAD

**Issue by D3vil0p3r** [Aylur/gnome-extensions#7]
Hello,
I'm using Arch Linux with GNOME 43, and you know, your GNOME extension is wonderful.

What I noted is that, when I open the dash, it is not taking the avatar of my user account:

![image](https://user-images.githubusercontent.com/83867734/200049103-8182c7fc-bf59-4588-9781-82cef1d7e978.png)

My avatar is located in `$HOME/.face`. How can I solve it? Is it a permission issue?

**Comment by Aylur** [comment]
How did you set your avatar? If you use gnome-settings it should create a file at /var/lib/AccountsService/icons/[user name]
That is where the dash is searching for

**Comment by D3vil0p3r** [comment]
> How did you set your avatar? If you use gnome-settings it should create a file at /var/lib/AccountsService/icons/[user name] That is where the dash is searching for

Hello. I know that Linux set the path of the icon not in `/var/lib/AccountsService/icons/[user name]` but inside `/var/lib/AccountsService/users/[user name]` file and here I have the path of my avatar (that works on the Login Manager):
```
[User]
Session=
XSession=gnome
Icon=/home/athena/.face
SystemAccount=false
```

**Comment by Aylur** [comment]
Just tried using a symlink, that seems to work

**Comment by D3vil0p3r** [comment]
> Just tried using a symlink, that seems to work

Does it work with `/var/lib/AccountsService/icons/[user name]` pr `/var/lib/AccountsService/users/[user name]`

**Comment by Aylur** [comment]
`/var/lib/AccountsService/icons/[user name]`

**Comment by D3vil0p3r** [comment]
> `/var/lib/AccountsService/icons/[user name]`

Which gsettings argument you use for having that path? And which distro are u using?

**Comment by Aylur** [comment]
I am not using gsettings at all for this. Isn't that path an xdg spec? I am on Fedora 36

**Comment by D3vil0p3r** [comment]
> I am not using gsettings at all for this. Isn't that path an xdg spec? I am on Fedora 36

Maybe on Arch Linux is different. Is it possible to make the extension to check also in the path I specified for the avatar?
