### ISSUE TITLE
It screwed up my terminal and quick tiles after uninstalling!

### ISSUE THREAD

**Issue by RVFET** [Aylur/gnome-extensions#72]
If your extensions does some irreversible changes to configs or overrides user defined ones then **DO A FREAKING BACKUP OF THE CURRENT ONE BEFORE OVERRIDING!**

I got some random tab/spaces on my terminal prompts (ZSH/ohmyzsh/headline zsh theme) after uninstalling this crap of an extension that I can't possibly find what did this thing have done to cause it, now my terminal looks broken and I'll lose my configuration that I built over all these years! Thanks!

**Comment by Aylur** [comment]
This extension only writes to `~/.cache`, it is not writing any config, and it especially doesn't touch any terminal config
