### ISSUE TITLE
Can't disable background clock

### ISSUE THREAD

**Issue by gaunh0** [Aylur/gnome-extensions#8]
Hello.
Thanks for the great extension, but I have a small problem: I can't disable the background clock.  Can you put this feature in the next version?

**Comment by Kertrix** [comment]
In the settings, I replaced the white color by transparent, and it hid it.

**Comment by Aylur** [comment]
Yeah sorry about, that forgot to add it to the prefs. Settings the color to transparent seems like a good idea for now.

**Comment by jwdotpark** [comment]
Is there anyway to disable the background clock at all? Overview animation has been pretty laggy and I think background clock is the culprit but can't disable it.

Disable the extension entirely removes the overview laggy animation FYI!

**Comment by XMelph** [comment]
The background clock also seems a bit laggy on my PC too. The only way to fix this for me was to delete all background clock codes inside the extension folder.

**Comment by jwdotpark** [comment]
Fantastic!!
